AutomatedTellerMachine/Controllers/CheckingAccountController.cs
using AutomatedTellerMachine.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;


namespace AutomatedTellerMachine.Models
{
    [Authorize]
    public class CheckingAccountController : Controller
    {
        private IApplicationDbContext db = new IApplicationDbContext();

        // GET: CheckingAccount
        public ActionResult Index()
        {
            
            return View();
        }

        // GET: CheckingAccount/Details/
        public ActionResult Details()
        {
            var userId = User.Identity.GetUserId();
            //var checkingAccount = new CheckingAccount { AccountNumber = "0000123456", LastName = "Dailey", FirstName = "Smithy", Balance = 500 };
            var checkingAccount = db.CheckingAccounts.Where(c => c.ApplicationUserId == userId).First();
            return View(checkingAccount);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult DetailsForAdmin(int id)
        {
            var checkingAccount = db.CheckingAccounts.Find(id);
            return View("Details", checkingAccount);
        }

        [Authorize(Roles ="Admin")]
        public ActionResult List()
        {
            return View(db.CheckingAccounts.ToList());
        }

        public ActionResult Statement(int id)
        {
            var checkingAccount = db.CheckingAccounts.Find(id);
            return View(checkingAccount.Transactions.ToList());
        }

        // GET: CheckingAccount/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CheckingAccount/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CheckingAccount/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CheckingAccount/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CheckingAccount/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CheckingAccount/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

AutomatedTellerMachine/Controllers/HomeController.cs
using AutomatedTellerMachine.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;

namespace AutomatedTellerMachine.Controllers
{
    public class HomeController : Controller
    {
        private IApplicationDbContext db = new IApplicationDbContext();

        // get /home/index
        [Authorize]
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var checkingAccountId = db.CheckingAccounts.Where(c => c.ApplicationUserId == userId).First().Id;
            //var checkingAccountId  = db.CheckingAccounts.Where(c => c.AccountNumber == userId).First().Id;
            ViewBag.CheckingAccountId = checkingAccountId;
            var manager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            var user = manager.FindById(userId);
            ViewBag.Pin = user.Pin;
            return View();
        }

        // get /home/about
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        // get /home/contact
        public ActionResult Contact()
        {
            ViewBag.TheMessage = "Having trouble? Send us a message.";

            return View();
        }

        [HttpPost]
        public ActionResult Contact(string message)
        {
            // send the message to someone
            ViewBag.TheMessage = "Thanks!, we got your message.";

            return PartialView("_ContactThanks");
        }

        public ActionResult Foo()
        {
            return View("about");
        }

        public ActionResult Serial(string letterCase)
        {
            var serial = "ASPNETMVC5ATM1";
            if (letterCase == "lower")
            {
                return Content(serial.ToLower());
            }
            //return new HttpStatusCodeResult(403);
            return Json(new { name = "serial", value = serial }, JsonRequestBehavior.AllowGet);
        }
    }
}

AutomatedTellerMachine/Controllers/TransactionController.cs
using AutomatedTellerMachine.Models;
using AutomatedTellerMachine.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutomatedTellerMachine.Controllers
{
    [Authorize]
    public class TransactionController : Controller
    {
        public IApplicationDbContext db = new IApplicationDbContext();

        // GET: Transaction/Deposit
        public ActionResult Deposit( int checkingAccountId)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Deposit(Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                db.Transactions.Add(transaction);
                db.SaveChanges();
                var service = new CheckingAccountService(db);
                service.UpdateBalance(transaction.CheckingAccountId);
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        public ActionResult Transfer(int checkingAccountId)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Transfer(TransferViewModel transfer)
        {
            // check for available funds
            var sourceCheckingAccount = db.CheckingAccounts.Find(transfer.CheckingAccountId);
            if (sourceCheckingAccount.Balance < transfer.Amount)
            {
                ModelState.AddModelError("Amount", "You have insufficient funds!");
            }

            // check for a vaild destination account
            var destinationCheckingAccount = db.CheckingAccounts.Where(c => c.AccountNumber == transfer.DestinationCheckingAccountNumber).FirstOrDefault();
            if (destinationCheckingAccount == null)
            {
                ModelState.AddModelError("DestinationCheckingAccountNumber", "Invaild destination account number");
            }

            // add debit/credit transactions and updates accouint balances
            if (ModelState.IsValid)
            {
                db.Transactions.Add(new Transaction { CheckingAccountId = transfer.CheckingAccountId, Amount = -transfer.Amount });
                db.Transactions.Add(new Transaction { CheckingAccountId = destinationCheckingAccount.Id, Amount = transfer.Amount });
                db.SaveChanges();

                var service = new CheckingAccountService(db);
                service.UpdateBalance(transfer.CheckingAccountId);
                service.UpdateBalance(destinationCheckingAccount.Id);

                return PartialView("_TransferSuccess", transfer);
            }
            return PartialView("_TransferForm");

        }

        public ActionResult Withdrawal(int checkingAccountId)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Withdrawal(Transaction transaction)
        {
            var checkingAccount = db.CheckingAccounts.Find(transaction.CheckingAccountId);
            if (checkingAccount.Balance < transaction.Amount)
            {
                ModelState.AddModelError("Amount", "you have insufficient funds!");
            }

            if (ModelState.IsValid)
            {
                transaction.Amount = -transaction.Amount;
                db.Transactions.Add(transaction);
                db.SaveChanges();

                var service = new CheckingAccountService(db);
                service.UpdateBalance(transaction.CheckingAccountId);
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        public ActionResult QuickCash(int checkingAccountId, decimal amount)
        {
            var sourceCheckingAccount = db.CheckingAccounts.Find(checkingAccountId);
            var balance = sourceCheckingAccount.Balance;
            if (balance < amount)
            {
                return View("QuickCashInsufficientFunds");
            }

            db.Transactions.Add(new Transaction { CheckingAccountId = checkingAccountId, Amount = -amount });
            db.SaveChanges();

            var service = new CheckingAccountService(db);
            service.UpdateBalance(checkingAccountId);
            return RedirectToAction("Index", "Home");
        }


    }
}

AutomatedTellerMachine/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AutomatedTellerMachine/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>


<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

<div id="formSection">
<h3>@ViewBag.TheMessage</h3>
    <form method="post" id="contactForm">
        <textarea name="message" id="message" maxlength="150" data-bind="value:message,valueUpdate:'input'"></textarea>
        <input type="submit" value="Send" />
        <span data-bind="text:charactersRemaining"></span> characters remaining
    </form>
    <img src="~/Content/Images/progress.gif" id="progress" style="display:none" />
</div>

@section scripts
{
    <script src="~/Scripts/knockout-3.4.2.js"></script>
    <script>
        function ContactViewModel() {
            var self = this;
            self.message = ko.observable('')
            self.charactersRemaining = ko.computed(function() {
                return 150 - self.message().length;
            })
        }
        ko.applyBindings(new ContactViewModel());
    </script>


    <script>
        $('#contactForm').submit(function () {
            $('#progress').show();
            $.post('', { message: $('#message').val() })
                .done(function (response) {
                //$('#formSection').html(response) {
                    setTimeout(function() { $('#formSection').html(response); }, 2000);
                });
            return false;
        });
    </script>    
}

@*
<div id="formSection">
    @using (Ajax.BeginForm(new AjaxOptions { HttpMethod = "post", InsertionMode = InsertionMode.Replace, UpdateTargetId = "formSection" }))

    {
        <textarea name="message"></textarea>
        <input type="submit" value="Send" />
    }
</div>

@section scripts
    {
        <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    }
*@

AutomatedTellerMachine/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@*
<div class="jumbotron">
    <h1>Middle Vally Commuity Bank</h1>
    <p class="lead">Middle Vally Commuity Bank offers the first-ever web-based ATM. Give it a try today!</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Powered by ASP.NET &raquo;</a></p>
</div>
    *@

<div class="row">
    <div class="col-md-6 margin-top-60">
        <a href="@Url.Action("Withdrawal", "Transaction", new { checkingAccountId = ViewBag.CheckingAccountId})" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-circle-arrow-down"></span> Withdrawal</a>
        <a href="@Url.Action("QuickCash", "Transaction", new { checkingAccountId = ViewBag.CheckingAccountId, amount = 100}) " class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-flash"></span> Quick Cash $100</a>
        <a href="@Url.Action("Details", "CheckingAccount")" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-question-sign"></span> Balance Inquiry</a>
    </div>

    
    
        <div class="col-md-6 margin-top-60">
            <a href="@Url.Action("Statement","CheckingAccount", new { id = ViewBag.CheckingAccountId })" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-print"></span> Print Statement</a>
            <a href="@Url.Action("Transfer", "Transaction", new {checkingAccountId = ViewBag.CheckingAccountId})" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-transfer"></span> Transfer Funds</a>
            <a href="@Url.Action("Deposit", "Transaction", new {checkingAccountId = ViewBag.CheckingAccountId})" class="btn btn-primary btn-large btn-block"><span class="glyphicon glyphicon-circle-arrow-up"></span> Deposit</a>
        </div>

    

        @*<div class="col-md-4">
                <h2>Register</h2>
                <p>
                   Open an accouint with us
                </p>
                <p>@Html.ActionLink("Register", "Register", "Account", null, new {@class="btn btn-default"})</p>
            </div>
            <div class="col-md-4">
                <h2>Log in</h2>
                <p>Access your existing account.</p>
                <p>@Html.ActionLink("Log in", "Login", "Account", null, new { @class = "btn btn-default" })</p>
            </div>
        *@

    </div>

@ViewBag.Pin
@* 
You are using @Request.Browser.Browser, and that's OK! Email us at supportmvcatm.com if you have any problems. Or send us a tweet @@mvcatm.

@{ var amounts = new List<Decimal> { 100, 25.50m, -40, 275.99m, -8.75m };
}

<ul>
    @foreach (decimal amount in amounts)
    {
        <li>@formatAmount(amount)</li>
    }
</ul>
   
 @helper formatAmount(decimal amount)
{
        var color = "green";
        if (amount < 0)
        {
            color = "red";
        }
    <span style="color:@color">@String.Format("{0:c}", amount)</span>
    }

*@

AutomatedTellerMachine/Views/Home/_ContactThanks.cshtml
<h3>@ViewBag.TheMessage</h3>